/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonDev {
        "color": 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger' | 'light' | 'dark';
    }
    interface CardDev {
    }
    interface CardDevBody {
    }
    interface CardDevFooter {
    }
    interface ModalBackdropDev {
    }
    interface ModalBodyDev {
        "content": string;
        "head": string;
        "open": () => Promise<void>;
    }
    interface ModalDev {
        "content": string;
        "head": string;
        "open": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLButtonDevElement extends Components.ButtonDev, HTMLStencilElement {
    }
    var HTMLButtonDevElement: {
        prototype: HTMLButtonDevElement;
        new (): HTMLButtonDevElement;
    };
    interface HTMLCardDevElement extends Components.CardDev, HTMLStencilElement {
    }
    var HTMLCardDevElement: {
        prototype: HTMLCardDevElement;
        new (): HTMLCardDevElement;
    };
    interface HTMLCardDevBodyElement extends Components.CardDevBody, HTMLStencilElement {
    }
    var HTMLCardDevBodyElement: {
        prototype: HTMLCardDevBodyElement;
        new (): HTMLCardDevBodyElement;
    };
    interface HTMLCardDevFooterElement extends Components.CardDevFooter, HTMLStencilElement {
    }
    var HTMLCardDevFooterElement: {
        prototype: HTMLCardDevFooterElement;
        new (): HTMLCardDevFooterElement;
    };
    interface HTMLModalBackdropDevElement extends Components.ModalBackdropDev, HTMLStencilElement {
    }
    var HTMLModalBackdropDevElement: {
        prototype: HTMLModalBackdropDevElement;
        new (): HTMLModalBackdropDevElement;
    };
    interface HTMLModalBodyDevElement extends Components.ModalBodyDev, HTMLStencilElement {
    }
    var HTMLModalBodyDevElement: {
        prototype: HTMLModalBodyDevElement;
        new (): HTMLModalBodyDevElement;
    };
    interface HTMLModalDevElement extends Components.ModalDev, HTMLStencilElement {
    }
    var HTMLModalDevElement: {
        prototype: HTMLModalDevElement;
        new (): HTMLModalDevElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-dev": HTMLButtonDevElement;
        "card-dev": HTMLCardDevElement;
        "card-dev-body": HTMLCardDevBodyElement;
        "card-dev-footer": HTMLCardDevFooterElement;
        "modal-backdrop-dev": HTMLModalBackdropDevElement;
        "modal-body-dev": HTMLModalBodyDevElement;
        "modal-dev": HTMLModalDevElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonDev {
        "color"?: 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger' | 'light' | 'dark';
    }
    interface CardDev {
    }
    interface CardDevBody {
    }
    interface CardDevFooter {
    }
    interface ModalBackdropDev {
    }
    interface ModalBodyDev {
        "content"?: string;
        "head"?: string;
        "onClose"?: (event: CustomEvent<any>) => void;
    }
    interface ModalDev {
        "content"?: string;
        "head"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "button-dev": ButtonDev;
        "card-dev": CardDev;
        "card-dev-body": CardDevBody;
        "card-dev-footer": CardDevFooter;
        "modal-backdrop-dev": ModalBackdropDev;
        "modal-body-dev": ModalBodyDev;
        "modal-dev": ModalDev;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-dev": LocalJSX.ButtonDev & JSXBase.HTMLAttributes<HTMLButtonDevElement>;
            "card-dev": LocalJSX.CardDev & JSXBase.HTMLAttributes<HTMLCardDevElement>;
            "card-dev-body": LocalJSX.CardDevBody & JSXBase.HTMLAttributes<HTMLCardDevBodyElement>;
            "card-dev-footer": LocalJSX.CardDevFooter & JSXBase.HTMLAttributes<HTMLCardDevFooterElement>;
            "modal-backdrop-dev": LocalJSX.ModalBackdropDev & JSXBase.HTMLAttributes<HTMLModalBackdropDevElement>;
            "modal-body-dev": LocalJSX.ModalBodyDev & JSXBase.HTMLAttributes<HTMLModalBodyDevElement>;
            "modal-dev": LocalJSX.ModalDev & JSXBase.HTMLAttributes<HTMLModalDevElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
