/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonDev {
        "color": 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger' | 'light' | 'dark';
    }
    interface CardDev {
    }
    interface CardDevBody {
    }
    interface CardDevFooter {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLButtonDevElement extends Components.ButtonDev, HTMLStencilElement {
    }
    var HTMLButtonDevElement: {
        prototype: HTMLButtonDevElement;
        new (): HTMLButtonDevElement;
    };
    interface HTMLCardDevElement extends Components.CardDev, HTMLStencilElement {
    }
    var HTMLCardDevElement: {
        prototype: HTMLCardDevElement;
        new (): HTMLCardDevElement;
    };
    interface HTMLCardDevBodyElement extends Components.CardDevBody, HTMLStencilElement {
    }
    var HTMLCardDevBodyElement: {
        prototype: HTMLCardDevBodyElement;
        new (): HTMLCardDevBodyElement;
    };
    interface HTMLCardDevFooterElement extends Components.CardDevFooter, HTMLStencilElement {
    }
    var HTMLCardDevFooterElement: {
        prototype: HTMLCardDevFooterElement;
        new (): HTMLCardDevFooterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-dev": HTMLButtonDevElement;
        "card-dev": HTMLCardDevElement;
        "card-dev-body": HTMLCardDevBodyElement;
        "card-dev-footer": HTMLCardDevFooterElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonDev {
        "color"?: 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger' | 'light' | 'dark';
    }
    interface CardDev {
    }
    interface CardDevBody {
    }
    interface CardDevFooter {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "button-dev": ButtonDev;
        "card-dev": CardDev;
        "card-dev-body": CardDevBody;
        "card-dev-footer": CardDevFooter;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-dev": LocalJSX.ButtonDev & JSXBase.HTMLAttributes<HTMLButtonDevElement>;
            "card-dev": LocalJSX.CardDev & JSXBase.HTMLAttributes<HTMLCardDevElement>;
            "card-dev-body": LocalJSX.CardDevBody & JSXBase.HTMLAttributes<HTMLCardDevBodyElement>;
            "card-dev-footer": LocalJSX.CardDevFooter & JSXBase.HTMLAttributes<HTMLCardDevFooterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
